# Blueprint/pages/dashboard.py
import streamlit as st
from dotenv import load_dotenv
load_dotenv()                  
import streamlit as st
from datetime import datetime
import logging
from typing import List, Dict
import os
import pandas as pd


# ======================
# MOCK DATA MODE SETUP
# ======================
USE_MOCK = os.getenv("USE_MOCK_DATA", "false").lower() == "true"


if USE_MOCK:
    # Mock database functions (using Streamlit session state)
    def get_tasks():
        if 'mock_tasks' not in st.session_state:
            st.session_state.mock_tasks = [
                {
                    "_id": "mock1",
                    "title": "Mock Task 1: Quote for Freezer Units",
                    "description": "Attached is the final quote for 12 walk-in freezer units. Installation & calibration included.",
                    "quote": "$12,500.00",
                    "assigned_to": "Andrew",
                    "notes": "Follow up with vendor on delivery date.",
                    "date": "2025-06-01",
                    "status": "To Do",
                    "exchange_id": "mock_exchange_id_1",
                    "created_at": "2024-05-26T10:00:00Z"
                },
                {
                    "_id": "mock2",
                    "title": "Mock Task 2: Permit Approved",
                    "description": "Your electrical permit for the downtown location has been approved. Valid for 6 months from issuance.",
                    "quote": "$0.00",
                    "assigned_to": "Unassigned",
                    "notes": "Schedule work within permit validity period.",
                    "date": "2025-05-30",
                    "status": "In Progress",
                    "exchange_id": "mock_exchange_id_2",
                    "created_at": "2024-05-26T10:05:00Z"
                },
                {
                    "_id": "mock3",
                    "title": "Mock Task 3: Concrete Pour Delayed",
                    "description": "Due to heavy rain, the scheduled pour for Aisle 3 is pushed to next Tuesday. Please adjust site fencing.",
                    "quote": "$0.00",
                    "assigned_to": "Mike",
                    "notes": "Notify site crew and update safety barriers.",
                    "date": "2025-06-04",
                    "status": "To Do",
                    "exchange_id": "mock_exchange_id_3",
                    "created_at": "2024-05-26T10:10:00Z"
                }
            ]
        return st.session_state.mock_tasks


else:
    # Real mode: Import actual implementations
    from db import get_tasks


# Configure logging
logging.basicConfig(level=logging.INFO)
logger = logging.getLogger(__name__)


# Page config
st.set_page_config(
    page_title="Blueprint Dashboard", 
    page_icon="📊",
    layout="wide"
)

st.title("📊 Blueprint Task Dashboard")
st.caption("View and analyze raw task data")


# Sidebar navigation (auto-generated by Streamlit for multi-page apps)
# We'll add a refresh button here instead
with st.sidebar:
    st.header("🔧 Dashboard Controls")
    if st.button("🔄 Refresh Data", use_container_width=True):
        st.rerun()
    st.divider()
    st.subheader("📊 Stats")
    tasks = get_tasks()
    st.metric("Total Tasks", len(tasks))
    st.metric("To Do", len([t for t in tasks if t["status"] == "To Do"]))
    st.metric("In Progress", len([t for t in tasks if t["status"] == "In Progress"]))
    st.metric("Done", len([t for t in tasks if t["status"] == "Done"]))


# Main dashboard content
tasks = get_tasks()

if not tasks:
    st.warning("No tasks found in the database.")
    st.info("Try syncing emails from the main Kanban board to generate some tasks.")
else:
    # Convert to DataFrame for better display
    df = pd.DataFrame(tasks)
    
    # Reorder columns for clarity
    cols_order = [
        "_id", "title", "date", "assigned_to", "quote", 
        "quote_type", "quote_assignee", "notes", "status", 
        "exchange_id", "created_at"
    ]
    
    # Only include columns that exist in the data
    existing_cols = [col for col in cols_order if col in df.columns]
    df = df[existing_cols]
    
    # Display the dataframe
    st.subheader("📋 Raw Task Data")
    st.dataframe(
        df,
        use_container_width=True,
        hide_index=True,
        column_config={
            "_id": "Task ID",
            "title": "Task Title",
            "date": "Due Date",
            "assigned_to": "Assigned To",
            "quote": "Quote Amount",
            "quote_type": "Quote Type",
            "quote_assignee": "Quote Assignee",
            "notes": "Notes",
            "status": "Status",
            "exchange_id": "Exchange ID",
            "created_at": "Created At"
        }
    )
    
    # Additional analytics
    st.divider()
    st.subheader("📈 Task Analytics")
    
    col1, col2 = st.columns(2)
    
    with col1:
        # Status distribution
        status_counts = df['status'].value_counts()
        st.bar_chart(status_counts)
        
    with col2:
        # Assignee distribution (top 5)
        assignee_counts = df['assigned_to'].value_counts().head(5)
        st.bar_chart(assignee_counts)
    
    # Download button for CSV
    csv = df.to_csv(index=False).encode('utf-8')
    st.download_button(
        label="📥 Download Data as CSV",
        data=csv,
        file_name="blueprint_tasks.csv",
        mime="text/csv",
        use_container_width=True
    )
